import Ogdoad.FifoTreeTrace
import Ogdoad.FifoCrossExitIncidence

/-!
# A root-prefix queue-cut target is not ancestry-complete

This file gives an exact four-label countermodel to the tempting
root-specific invariant saying that every occurrence's prefix plus current
queue-cut vector belongs to the root policy's terminal affine hull.

Label `3` is the prospective dummy.  For the displayed positional policy of
the outside player (`true`), the compatible terminal real-edge moments are
contained in the two-dimensional span generated by `01 + 12` and `02`.
Nevertheless the reachable occurrence after `O₂,O₀,C₂` has prefix
`01 + 12`, queue cut `01`, hence decorated target `12`, which is outside
that span.  The target therefore needs more ancestry than the exact prefix
and current public queue cut.

This is a route countermodel, not a counterexample to FIFO linking: zero is
still one of the root terminal moments.
-/

namespace Ogdoad.Fifo

noncomputable section

universe u

/-- Universal public queue-cut vector used in the root-prefix proposal. -/
def rootQueueCutVector {V : Type u} [DecidableEq V]
    (s : PublicState V) : EdgeVector V :=
  (s.queue.map (liveStarVector s.untouched)).sum

@[simp] theorem graphEvaluation_rootQueueCutVector
    {V : Type u} [DecidableEq V] (G : SimpleGraph V) (s : PublicState V) :
    graphEvaluation G (rootQueueCutVector s) =
      queueCut G s.untouched s.queue := by
  rw [rootQueueCutVector, map_list_sum, queueCut]
  apply congrArg List.sum
  rw [List.map_map]
  apply List.map_congr_left
  intro v hv
  exact graphEvaluation_liveStarVector G s.untouched v

/-- Scalar meaning of the decorated prefix target.  Along an initial-root
strategy occurrence, graph evaluation of `prefix + current queue cut` is
exactly the current score.  Thus every score-zero occurrence places this
candidate on the separator's homogeneous sheet, whereas all root response
points lie on its affine-one sheet. -/
theorem StrategyPrefix.graphEvaluation_prefix_add_queueCut_eq_score
    {V : Type u} [Fintype V] [DecidableEq V]
    {G : SimpleGraph V} {seat : Bool} {s : State V}
    {root : OddStrategy G seat (initial (V := V))}
    {child : OddStrategy G seat s} {p : EdgeVector V}
    (hp : StrategyPrefix G seat root child p) :
    graphEvaluation G (p + rootQueueCutVector s.public) = s.score := by
  rw [map_add, hp.graphEvaluation_eq_potential_add wellFormed_initial,
    graphEvaluation_rootQueueCutVector]
  simp only [potential, initial, State.public, queueCut, List.map_nil,
    List.sum_nil, zero_add]
  let q := (List.map (flip G s.untouched) s.queue).sum
  change s.score + q + q = s.score
  calc
    s.score + q + q = s.score + (q + q) := by abel
    _ = s.score := by rw [CharTwo.add_self_eq_zero, add_zero]

/-- In particular the root-prefix queue-cut target is *necessarily absent*
at every score-zero occurrence of an actual odd counterstrategy.  This is
the separator-dual reason that a pointwise descendant induction cannot prove
the root affine contraction: the desired local target is on the wrong scalar
sheet exactly at the minimum-bad states used by the strategy proof. -/
theorem StrategyPrefix.not_affineResponseMoment_prefix_add_queueCut_of_score_zero
    {V : Type u} [Fintype V] [DecidableEq V]
    {G : SimpleGraph V} {seat : Bool} {s : State V}
    {root : OddStrategy G seat (initial (V := V))}
    {child : OddStrategy G seat s} {p : EdgeVector V}
    (hp : StrategyPrefix G seat root child p) (hs : s.score = 0) :
    ¬AffineResponseMoment G seat root (p + rootQueueCutVector s.public) := by
  intro hresponse
  have hone := hresponse.graphEvaluation_eq wellFormed_initial
  have hzero := hp.graphEvaluation_prefix_add_queueCut_eq_score
  rw [hs] at hzero
  rw [hzero] at hone
  simp [potential, initial, queueCut] at hone

/-- All graph-independent legal children on `Fin 4`, in label order. -/
def legalPublicChildrenFour (s : PublicState (Fin 4)) :
    List (Move (Fin 4) × PublicState (Fin 4)) :=
  ([Move.open 0, Move.open 1, Move.open 2, Move.open 3,
      Move.close, Move.pass]).filterMap fun m ↦
    (publicStep s m).map fun t ↦ (m, t)

/-- The two exceptional choices in the counterpolicy.  Everywhere else the
policy selects the least legal OPEN, and drains when no OPEN remains. -/
def prefixQueueCutCounterPolicy (s : PublicState (Fin 4)) : Move (Fin 4) :=
  if s.untouched = {1, 3} ∧ s.queue = [0] ∧ s.ko = false then .close
  else if s.untouched = {0, 2, 3} ∧ s.queue = [1] ∧ s.ko = true then .open 3
  else if 0 ∈ s.untouched then .open 0
  else if 1 ∈ s.untouched then .open 1
  else if 2 ∈ s.untouched then .open 2
  else if 3 ∈ s.untouched then .open 3
  else if s.ko then .pass
  else .close

/-- Bounded validity checker for a positional policy.  At full-fan nodes it
checks every legal child; at selected nodes it rejects an illegal policy
move. -/
def publicPolicyValidFour
    (policy : PublicState (Fin 4) → Move (Fin 4)) :
    Nat → PublicState (Fin 4) → Bool
  | 0, _ => false
  | fuel + 1, s =>
      if s.untouched = ∅ ∧ s.queue = [] then true
      else if s.toMove = false then
        (legalPublicChildrenFour s).all fun child ↦
          publicPolicyValidFour policy fuel child.2
      else
        match publicStep s (policy s) with
        | none => false
        | some t => publicPolicyValidFour policy fuel t

/-- The displayed positional rule is legal on its entire compatible tree. -/
theorem prefixQueueCutCounterPolicy_valid :
    publicPolicyValidFour prefixQueueCutCounterPolicy 30
      (initial (V := Fin 4)).public = true := by
  native_decide

/-- Terminal moments of every leaf compatible with a positional policy,
restricted to the three real coordinates `01,02,12`. -/
def policyLeafRealMomentsFour
    (policy : PublicState (Fin 4) → Move (Fin 4)) :
    Nat → PublicState (Fin 4) → List (Bool × Bool × Bool)
  | 0, _ => []
  | fuel + 1, s =>
      if s.untouched = ∅ ∧ s.queue = [] then
        [(false, false, false)]
      else if s.toMove = false then
        (legalPublicChildrenFour s).flatMap fun child ↦
          (policyLeafRealMomentsFour policy fuel child.2).map fun z ↦
            ((moveEdgeBit s child.1 0 1).xor z.1,
              (moveEdgeBit s child.1 0 2).xor z.2.1,
              (moveEdgeBit s child.1 1 2).xor z.2.2)
      else
        match publicStep s (policy s) with
        | none => []
        | some t =>
            (policyLeafRealMomentsFour policy fuel t).map fun z ↦
              ((moveEdgeBit s (policy s) 0 1).xor z.1,
                (moveEdgeBit s (policy s) 0 2).xor z.2.1,
                (moveEdgeBit s (policy s) 1 2).xor z.2.2)

/-- Coordinatewise addition in the three real-edge coordinates. -/
def xorRealMoment (a b : Bool × Bool × Bool) : Bool × Bool × Bool :=
  (a.1.xor b.1, a.2.1.xor b.2.1, a.2.2.xor b.2.2)

/-- The real-edge coordinates of one universal move label. -/
def moveRealMomentFour (s : PublicState (Fin 4)) (m : Move (Fin 4)) :
    Bool × Bool × Bool :=
  (moveEdgeBit s m 0 1, moveEdgeBit s m 0 2, moveEdgeBit s m 1 2)

/-- The three real coordinates of the current universal queue cut. -/
def queueCutRealMomentFour (s : PublicState (Fin 4)) :
    Bool × Bool × Bool :=
  (decide ((0 ∈ s.untouched ∧ 1 ∈ s.queue) ∨
      (1 ∈ s.untouched ∧ 0 ∈ s.queue)),
   decide ((0 ∈ s.untouched ∧ 2 ∈ s.queue) ∨
      (2 ∈ s.untouched ∧ 0 ∈ s.queue)),
   decide ((1 ∈ s.untouched ∧ 2 ∈ s.queue) ∨
      (2 ∈ s.untouched ∧ 1 ∈ s.queue)))

/-- Ternary closure of a finite leaf family: its affine hull over `F₂`. -/
inductive RealMomentAffineHull (xs : List (Bool × Bool × Bool)) :
    (Bool × Bool × Bool) → Prop
  | leaf {z} (hz : z ∈ xs) : RealMomentAffineHull xs z
  | ternary {x y z}
      (hx : RealMomentAffineHull xs x)
      (hy : RealMomentAffineHull xs y)
      (hz : RealMomentAffineHull xs z) :
      RealMomentAffineHull xs
        (xorRealMoment (xorRealMoment x y) z)

/-- The linear sheet `01 = 12` is closed under ternary affine generation. -/
theorem RealMomentAffineHull.sheet
    {xs : List (Bool × Bool × Bool)}
    (hleaf : ∀ z ∈ xs, z.1 = z.2.2)
    {z : Bool × Bool × Bool} (hz : RealMomentAffineHull xs z) :
    z.1 = z.2.2 := by
  induction hz with
  | leaf hz => exact hleaf _ hz
  | ternary hx hy hz ihx ihy ihz =>
      simp only [xorRealMoment]
      simp [ihx, ihy, ihz]

/-- The exact root terminal real moments are nine zeroes, four copies of
`01+12`, and three copies of `02`. -/
theorem prefixQueueCutCounterPolicy_terminal_moments :
    policyLeafRealMomentsFour prefixQueueCutCounterPolicy 30
      (initial (V := Fin 4)).public =
    [(false, false, false), (false, false, false),
      (false, true, false), (false, true, false),
      (false, false, false), (false, false, false),
      (true, false, true), (true, false, true),
      (false, false, false), (false, false, false),
      (true, false, true), (true, false, true),
      (false, false, false), (false, false, false),
      (false, false, false), (false, true, false)] := by
  native_decide

/-- Every compatible terminal moment satisfies the affine equation
`coordinate 01 = coordinate 12`. -/
theorem prefixQueueCutCounterPolicy_terminal_sheet :
    ∀ z ∈ policyLeafRealMomentsFour prefixQueueCutCounterPolicy 30
        (initial (V := Fin 4)).public,
      z.1 = z.2.2 := by
  native_decide

/-- The occurrence reached by `O₂,O₀,C₂` is exactly the state with untouched
`{1,3}` and queue `[0]`. -/
theorem prefixQueueCutCounterPolicy_bad_occurrence :
    publicStep (initial (V := Fin 4)).public (.open 2) =
        some (⟨{0, 1, 3}, [2], true, true⟩ : PublicState (Fin 4)) ∧
    publicStep (⟨{0, 1, 3}, [2], true, true⟩ : PublicState (Fin 4))
        (.open 0) =
        some (⟨{1, 3}, [2, 0], false, false⟩ : PublicState (Fin 4)) ∧
    publicStep (⟨{1, 3}, [2, 0], false, false⟩ : PublicState (Fin 4))
        .close =
        some (⟨{1, 3}, [0], false, true⟩ : PublicState (Fin 4)) := by
  native_decide

/-- The displayed outside-player moves really are selected by the positional
policy along the bad occurrence. -/
theorem prefixQueueCutCounterPolicy_selected_moves :
    prefixQueueCutCounterPolicy
        (⟨{0, 1, 3}, [2], true, true⟩ : PublicState (Fin 4)) = .open 0 ∧
    prefixQueueCutCounterPolicy
        (⟨{1, 3}, [0], false, true⟩ : PublicState (Fin 4)) = .close := by
  native_decide

/-- Direct coordinate computation of the proposed decorated target at the
bad occurrence.  The two OPEN prefix contributes `01+12`; the current queue
cut contributes `01`; their sum is the isolated coordinate `12`. -/
theorem prefixQueueCutCounterPolicy_bad_decorated_computation :
    xorRealMoment
        (xorRealMoment
          (moveRealMomentFour (initial (V := Fin 4)).public (.open 2))
          (moveRealMomentFour
            (⟨{0, 1, 3}, [2], true, true⟩ : PublicState (Fin 4))
            (.open 0)))
        (queueCutRealMomentFour
          (⟨{1, 3}, [0], false, true⟩ : PublicState (Fin 4))) =
      (false, false, true) := by
  native_decide

/-- Zero is itself a compatible terminal moment, so the counterpolicy is not
a counterexample to the universal affine root conjecture. -/
theorem prefixQueueCutCounterPolicy_has_zero_terminal :
    (false, false, false) ∈
      policyLeafRealMomentsFour prefixQueueCutCounterPolicy 30
        (initial (V := Fin 4)).public := by
  native_decide

/-- The decorated prefix-plus-queue-cut target at the displayed occurrence is
the vector `12`, which violates the sheet equation obeyed by every root
terminal moment. -/
theorem prefixQueueCutCounterPolicy_decorated_target_off_sheet :
    let target : Bool × Bool × Bool := (false, false, true)
    target.1 ≠ target.2.2 := by
  decide

/-- Consequently the exact decorated occurrence target is outside the affine
hull of all root terminal moments of the counterpolicy. -/
theorem prefixQueueCutCounterPolicy_decorated_target_not_affine :
    ¬RealMomentAffineHull
      (policyLeafRealMomentsFour prefixQueueCutCounterPolicy 30
        (initial (V := Fin 4)).public)
      (false, false, true) := by
  intro htarget
  have hsheet := htarget.sheet
    prefixQueueCutCounterPolicy_terminal_sheet
  exact prefixQueueCutCounterPolicy_decorated_target_off_sheet hsheet

end

end Ogdoad.Fifo
