import Ogdoad.FifoNormalization

/-!
# Proof-indexed affine response spaces for FIFO linking

This module formalizes the proof-indexed affine object at the remaining
boundary of the arbitrary-graph FIFO linking problem.  It does **not** prove
the causal factor-extension hypothesis.

`AffineResponseMoment G seat h z` says that `z` belongs to the affine hull of
the terminal universal live-star moments compatible with one explicit
`OddWins` strategy tree `h`.  At an attacker node only the strategy's selected
child is retained; at a defender node every legal child may enter the hull.
Ternary closure is affine closure over `ZMod 2`.

The checked results are:

* every response moment evaluates on the current graph to the odd terminal
  defect relative to the current queue-cut potential;
* after quotienting out coordinates incident to an isolated dummy and all
  diagonal coordinates, zero
  cannot lie in the projected response affine space of an actual odd
  counterstrategy at the initial root;
* any supplied odd list of legal defender branches lifts through its child
  continuation spaces (the theorem does not assert that the list is complete);
* the unprojected continuation-coset condition
  `sum (prefix_i + base_i) = sum correction_i` implies root moment zero;
* proof-indexed ancestry paths let that cancellation couple different
  defender siblings and different FIFO-front levels; and
* a projected ancestry factor certificate in the real-edge quotient is
  sufficient for pointwise FIFO linking.

The unprojected `EdgeVector V` also contains coordinates incident to the
dummy.  Consequently the full-vector certificates below are deliberately
labelled as a stronger sufficient condition.  The exact affine target used
for an isolated-dummy graph is `RealEdgeQuotient V d`, the quotient by the
span of all dummy-incident and diagonal coordinates.

The missing theorem is to construct such an odd proof-indexed ancestry factor
certificate from an arbitrary attacker-pruned strategy tree on a board with
an isolated dummy.  None of the definitions or theorems below assumes that
construction.
-/

namespace Ogdoad.Fifo

noncomputable section

variable {V : Type*} [Fintype V] [DecidableEq V]

/-! ## The exact real-edge quotient -/

/-- The subspace generated by all universal edge coordinates incident to the
distinguished dummy.  The diagonal generator is harmless: simple-graph
evaluation kills it, and live-star vectors never create diagonal terms. -/
def dummyEdgeSpace (d : V) : Submodule (ZMod 2) (EdgeVector V) :=
  Submodule.span (ZMod 2)
    (Set.range fun v : V ↦ Finsupp.single s(d, v) 1)

/-- The subspace generated by diagonal coordinates.  These occur in the
universal `Sym2` carrier but not in live-star moments, and simple-graph
evaluation kills them. -/
def diagonalEdgeSpace : Submodule (ZMod 2) (EdgeVector V) :=
  Submodule.span (ZMod 2)
    (Set.range fun v : V ↦ Finsupp.single s(v, v) 1)

/-- The coordinates that do not represent real edges of the board. -/
def realEdgeNullSpace (d : V) : Submodule (ZMod 2) (EdgeVector V) :=
  dummyEdgeSpace d ⊔ diagonalEdgeSpace

/-- Universal edge moments modulo precisely the dummy-incident and diagonal
coordinates.  This is the real-edge coordinate space in quotient form. -/
abbrev RealEdgeQuotient (V : Type*) [DecidableEq V] (d : V) :=
  EdgeVector V ⧸ realEdgeNullSpace d

/-- Forget the non-real coordinates of a universal edge moment. -/
def realEdgeProjection (d : V) :
    EdgeVector V →ₗ[ZMod 2] RealEdgeQuotient V d :=
  (realEdgeNullSpace d).mkQ

omit [Fintype V] in
@[simp] theorem realEdgeProjection_dummy_single
    (d v : V) (c : ZMod 2) :
    realEdgeProjection d (Finsupp.single s(d, v) c) = 0 := by
  rw [realEdgeProjection, Submodule.mkQ_apply,
    Submodule.Quotient.mk_eq_zero]
  by_cases hc : c = 0
  · simp [hc]
  · have hgen : Finsupp.single s(d, v) 1 ∈ dummyEdgeSpace d := by
      exact Submodule.subset_span (Set.mem_range_self v)
    have hnull : Finsupp.single s(d, v) 1 ∈ realEdgeNullSpace d :=
      (show dummyEdgeSpace d ≤ realEdgeNullSpace d from
        le_sup_left) hgen
    simpa [smul_eq_mul, hc] using
      (realEdgeNullSpace d).smul_mem c hnull

omit [Fintype V] in
@[simp] theorem realEdgeProjection_diagonal_single
    (d v : V) (c : ZMod 2) :
    realEdgeProjection d (Finsupp.single s(v, v) c) = 0 := by
  rw [realEdgeProjection, Submodule.mkQ_apply,
    Submodule.Quotient.mk_eq_zero]
  by_cases hc : c = 0
  · simp [hc]
  · have hgen : Finsupp.single s(v, v) 1 ∈ diagonalEdgeSpace := by
      exact Submodule.subset_span (Set.mem_range_self v)
    have hnull : Finsupp.single s(v, v) 1 ∈ realEdgeNullSpace d :=
      (show diagonalEdgeSpace ≤ realEdgeNullSpace d from
        le_sup_right) hgen
    simpa [smul_eq_mul, hc] using
      (realEdgeNullSpace d).smul_mem c hnull

omit [Fintype V] in
/-- The real-edge projection genuinely forgets information: even the dummy
diagonal basis vector is nonzero before projection and zero afterwards. -/
theorem realEdgeProjection_not_injective (d : V) :
    ¬Function.Injective (realEdgeProjection d) := by
  intro hinj
  have heq :
      Finsupp.single s(d, d) (1 : ZMod 2) = (0 : EdgeVector V) := by
    apply hinj
    simp
  have hcoord := congrArg (fun z : EdgeVector V ↦ z s(d, d)) heq
  simp at hcoord

omit [Fintype V] [DecidableEq V] in
/-- An isolated graph functional kills the entire dummy-coordinate subspace. -/
theorem dummyEdgeSpace_le_graphEvaluation_ker
    {G : SimpleGraph V} {d : V} (hd : IsDummy G d) :
    dummyEdgeSpace d ≤
      LinearMap.ker ((graphEvaluation G).toZModLinearMap 2) := by
  rw [dummyEdgeSpace, Submodule.span_le]
  rintro z ⟨v, rfl⟩
  change graphEvaluation G (Finsupp.single s(d, v) 1) = 0
  rw [graphEvaluation_single]
  simp [adjacencyBit, hd v]

omit [Fintype V] [DecidableEq V] in
/-- A simple-graph functional kills every diagonal coordinate. -/
theorem diagonalEdgeSpace_le_graphEvaluation_ker (G : SimpleGraph V) :
    diagonalEdgeSpace ≤
      LinearMap.ker ((graphEvaluation G).toZModLinearMap 2) := by
  rw [diagonalEdgeSpace, Submodule.span_le]
  rintro z ⟨v, rfl⟩
  change graphEvaluation G (Finsupp.single s(v, v) 1) = 0
  rw [graphEvaluation_single]
  simp [adjacencyBit]

omit [Fintype V] [DecidableEq V] in
/-- An isolated graph functional kills every non-real coordinate. -/
theorem realEdgeNullSpace_le_graphEvaluation_ker
    {G : SimpleGraph V} {d : V} (hd : IsDummy G d) :
    realEdgeNullSpace d ≤
      LinearMap.ker ((graphEvaluation G).toZModLinearMap 2) := by
  rw [realEdgeNullSpace]
  exact sup_le
    (dummyEdgeSpace_le_graphEvaluation_ker hd)
    (diagonalEdgeSpace_le_graphEvaluation_ker G)

omit [Fintype V] in
/-- Vanishing in the real-edge quotient forces zero graph evaluation for an
isolated-dummy graph. -/
theorem graphEvaluation_eq_zero_of_realEdgeProjection_eq_zero
    {G : SimpleGraph V} {d : V} (hd : IsDummy G d)
    {z : EdgeVector V} (hz : realEdgeProjection d z = 0) :
    graphEvaluation G z = 0 := by
  have hzmem : z ∈ realEdgeNullSpace d := by
    rw [← Submodule.Quotient.mk_eq_zero, ← Submodule.mkQ_apply]
    exact hz
  have hker := realEdgeNullSpace_le_graphEvaluation_ker hd hzmem
  exact LinearMap.mem_ker.mp hker

/-- The affine hull of terminal universal live-star moments compatible with
one fixed explicit odd strategy. -/
inductive AffineResponseMoment (G : SimpleGraph V) (seat : Bool) :
    {s : State V} → OddWins G seat s → EdgeVector V → Prop
  | terminal (s : State V) (ht : Terminal s) (hs : s.score ≠ 0) :
      AffineResponseMoment G seat (OddWins.terminal s ht hs) 0
  | choose {s s' : State V} {hseat : s.toMove ≠ seat}
      {m : Move V} {hstep : step G s m = some s'}
      {hchild : OddWins G seat s'} {z : EdgeVector V}
      (tail : AffineResponseMoment G seat hchild z) :
      AffineResponseMoment G seat
        (OddWins.choose s hseat m s' hstep hchild) (moveLiveStar s m + z)
  | answerChild {s s' : State V} {hseat : s.toMove = seat}
      {hasMove : ∃ m u, step G s m = some u}
      {hchildren : ∀ m u, step G s m = some u → OddWins G seat u}
      {m : Move V} {hstep : step G s m = some s'} {z : EdgeVector V}
      (tail : AffineResponseMoment G seat (hchildren m s' hstep) z) :
      AffineResponseMoment G seat
        (OddWins.answer s hseat hasMove hchildren) (moveLiveStar s m + z)
  | ternary {s : State V} {h : OddWins G seat s}
      {x y z : EdgeVector V}
      (hx : AffineResponseMoment G seat h x)
      (hy : AffineResponseMoment G seat h y)
      (hz : AffineResponseMoment G seat h z) :
      AffineResponseMoment G seat h (x + y + z)

omit [Fintype V] in
/-- Every response moment in an odd strategy evaluates to the odd terminal
defect relative to the current queue-cut potential. -/
theorem AffineResponseMoment.graphEvaluation_eq
    {G : SimpleGraph V} {seat : Bool} {s : State V}
    {h : OddWins G seat s} {z : EdgeVector V}
    (hr : AffineResponseMoment G seat h z) (hs : WellFormed s) :
    graphEvaluation G z = 1 + potential G s := by
  induction hr with
  | terminal s ht hscore =>
      have hs1 : s.score = 1 := zmod2_eq_one_of_ne_zero _ hscore
      rw [terminal_potential ht, hs1]
      simp [CharTwo.add_self_eq_zero]
  | @choose s s' hseat m hstep hchild z tail ih =>
      have hs' : WellFormed s' := wellFormed_step hs hstep
      have hpot := step_potential_eq_add_liveDegree hstep
      have heval := graphEvaluation_moveLiveStar G s m hs
      rw [map_add, heval, ih hs', hpot]
      cases m with
      | «open» v =>
          simp only
          calc
            liveDegree G s v + (1 + (potential G s + liveDegree G s v)) =
                (liveDegree G s v + liveDegree G s v) +
                  (1 + potential G s) := by abel
            _ = 1 + potential G s := by
              rw [CharTwo.add_self_eq_zero, zero_add]
      | close => simp
      | pass => simp
  | @answerChild s s' hseat hasMove hchildren m hstep z tail ih =>
      have hs' : WellFormed s' := wellFormed_step hs hstep
      have hpot := step_potential_eq_add_liveDegree hstep
      have heval := graphEvaluation_moveLiveStar G s m hs
      rw [map_add, heval, ih hs', hpot]
      cases m with
      | «open» v =>
          simp only
          calc
            liveDegree G s v + (1 + (potential G s + liveDegree G s v)) =
                (liveDegree G s v + liveDegree G s v) +
                  (1 + potential G s) := by abel
            _ = 1 + potential G s := by
              rw [CharTwo.add_self_eq_zero, zero_add]
      | close => simp
      | pass => simp
  | @ternary s h x y z hx hy hz ihx ihy ihz =>
      rw [map_add, map_add, ihx hs, ihy hs, ihz hs]
      rw [CharTwo.add_self_eq_zero, zero_add]

/-- Zero cannot already lie in the affine response space of an actual odd
strategy on the initial board: graph evaluation would send it to one. -/
theorem no_zero_affineResponseMoment_initial
    {G : SimpleGraph V} {seat : Bool}
    {h : OddWins G seat (initial (V := V))} :
    ¬AffineResponseMoment G seat h 0 := by
  intro hz
  have heval := hz.graphEvaluation_eq wellFormed_initial
  simp [potential, initial, queueCut] at heval

/-- The affine response space after forgetting non-real coordinates. -/
def ProjectedAffineResponseMoment (d : V) (G : SimpleGraph V) (seat : Bool)
    {s : State V} (h : OddWins G seat s) (q : RealEdgeQuotient V d) : Prop :=
  ∃ z, AffineResponseMoment G seat h z ∧ realEdgeProjection d z = q

/-- Zero cannot lie in the exact real-edge response affine space of an odd
counterstrategy on an isolated-dummy initial board. -/
theorem no_zero_projectedAffineResponseMoment_initial
    {G : SimpleGraph V} {d : V} {seat : Bool} (hd : IsDummy G d)
    {h : OddWins G seat (initial (V := V))} :
    ¬ProjectedAffineResponseMoment d G seat h 0 := by
  rintro ⟨z, hz, hproj⟩
  have heval := hz.graphEvaluation_eq wellFormed_initial
  have heval0 :=
    graphEvaluation_eq_zero_of_realEdgeProjection_eq_zero hd hproj
  rw [heval0] at heval
  simp [potential, initial, queueCut] at heval

/-- Differences of two moments in one fixed continuation affine space.  Over
`ZMod 2`, subtraction is addition. -/
def ResponseDirection (G : SimpleGraph V) (seat : Bool)
    {s : State V} (h : OddWins G seat s) (d : EdgeVector V) : Prop :=
  ∃ x y, AffineResponseMoment G seat h x ∧
    AffineResponseMoment G seat h y ∧ d = x + y

omit [Fintype V] in
/-- Every finite strategy continuation is nonempty, so its direction space
contains zero. -/
theorem ResponseDirection.zero
    {G : SimpleGraph V} {seat : Bool} {s : State V}
    (h : OddWins G seat s) : ResponseDirection G seat h 0 := by
  induction h with
  | terminal s ht hs =>
      exact ⟨(0 : EdgeVector V), 0, .terminal s ht hs, .terminal s ht hs,
        by simp⟩
  | choose s hseat m s' hstep hchild ih =>
      obtain ⟨x, y, hx, hy, hxy⟩ := ih
      have hpx : AffineResponseMoment G seat
          (OddWins.choose s hseat m s' hstep hchild)
          (moveLiveStar s m + x) :=
        .choose (hseat := hseat) (hstep := hstep) hx
      have hpy : AffineResponseMoment G seat
          (OddWins.choose s hseat m s' hstep hchild)
          (moveLiveStar s m + y) :=
        .choose (hseat := hseat) (hstep := hstep) hy
      refine ⟨_, _, hpx, hpy, ?_⟩
      symm
      calc
        (moveLiveStar s m + x) + (moveLiveStar s m + y) =
            (moveLiveStar s m + moveLiveStar s m) + (x + y) := by abel
        _ = 0 := by
          have hself : moveLiveStar s m + moveLiveStar s m = 0 := by
            ext e
            exact CharTwo.add_self_eq_zero ((moveLiveStar s m) e)
          rw [hself, zero_add, ← hxy]
  | answer s hseat hasMove hchildren ih =>
      have hasMove' := hasMove
      obtain ⟨m, s', hstep⟩ := hasMove'
      obtain ⟨x, y, hx, hy, hxy⟩ := ih m s' hstep
      have hpx : AffineResponseMoment G seat
          (OddWins.answer s hseat hasMove hchildren)
          (moveLiveStar s m + x) :=
        .answerChild (hseat := hseat) (hasMove := hasMove)
          (hchildren := hchildren) (hstep := hstep) hx
      have hpy : AffineResponseMoment G seat
          (OddWins.answer s hseat hasMove hchildren)
          (moveLiveStar s m + y) :=
        .answerChild (hseat := hseat) (hasMove := hasMove)
          (hchildren := hchildren) (hstep := hstep) hy
      refine ⟨_, _, hpx, hpy, ?_⟩
      symm
      calc
        (moveLiveStar s m + x) + (moveLiveStar s m + y) =
            (moveLiveStar s m + moveLiveStar s m) + (x + y) := by abel
        _ = 0 := by
          have hself : moveLiveStar s m + moveLiveStar s m = 0 := by
            ext e
            exact CharTwo.add_self_eq_zero ((moveLiveStar s m) e)
          rw [hself, zero_add, ← hxy]

omit [Fintype V] in
/-- The actual finite Bellman tree supplies at least one continuation
representative.  The open issue is their correlated selection, not
inhabitation of any one child affine space. -/
theorem exists_affineResponseMoment
    {G : SimpleGraph V} {seat : Bool} {s : State V}
    (h : OddWins G seat s) :
    ∃ z, AffineResponseMoment G seat h z := by
  obtain ⟨x, _, hx, _, _⟩ := ResponseDirection.zero h
  exact ⟨x, hx⟩

omit [Fintype V] in
/-- Every continuation direction is invisible to the current graph
functional, since its two endpoints have the same odd terminal defect. -/
theorem ResponseDirection.graphEvaluation_eq_zero
    {G : SimpleGraph V} {seat : Bool} {s : State V}
    {h : OddWins G seat s} {d : EdgeVector V}
    (hd : ResponseDirection G seat h d) (hs : WellFormed s) :
    graphEvaluation G d = 0 := by
  obtain ⟨x, y, hx, hy, rfl⟩ := hd
  rw [map_add, hx.graphEvaluation_eq hs, hy.graphEvaluation_eq hs]
  exact CharTwo.add_self_eq_zero _

omit [Fintype V] in
/-- Translating a response representative by a continuation direction stays
in the same affine response space. -/
theorem AffineResponseMoment.add_direction
    {G : SimpleGraph V} {seat : Bool} {s : State V}
    {h : OddWins G seat s} {a d : EdgeVector V}
    (ha : AffineResponseMoment G seat h a)
    (hd : ResponseDirection G seat h d) :
    AffineResponseMoment G seat h (a + d) := by
  obtain ⟨x, y, hx, hy, rfl⟩ := hd
  simpa [add_assoc] using AffineResponseMoment.ternary ha hx hy

omit [Fintype V] in
/-- The sum of any odd list of representatives from one response affine
space is again a representative. -/
theorem AffineResponseMoment.odd_list_sum
    {G : SimpleGraph V} {seat : Bool} {s : State V}
    {h : OddWins G seat s} :
    ∀ (zs : List (EdgeVector V)),
      zs.length % 2 = 1 →
      (∀ z ∈ zs, AffineResponseMoment G seat h z) →
      AffineResponseMoment G seat h zs.sum := by
  intro zs hodd hall
  match zs with
  | [] => simp at hodd
  | [x] => simpa using hall x (by simp)
  | [x, y] => simp at hodd
  | x :: y :: z :: rest =>
      let xyz := x + y + z
      have hx := hall x (by simp)
      have hy := hall y (by simp)
      have hz := hall z (by simp)
      have hxyz : AffineResponseMoment G seat h xyz := by
        exact AffineResponseMoment.ternary hx hy hz
      have hodd' : (xyz :: rest).length % 2 = 1 := by
        simp only [List.length_cons]
        simp only [List.length_cons] at hodd
        omega
      have hall' : ∀ w ∈ xyz :: rest,
          AffineResponseMoment G seat h w := by
        intro w hw
        simp only [List.mem_cons] at hw
        rcases hw with rfl | hw
        · exact hxyz
        · exact hall w (by simp [hw])
      have ih := AffineResponseMoment.odd_list_sum (xyz :: rest) hodd' hall'
      simpa [xyz, add_assoc] using ih
termination_by zs => zs.length

omit [Fintype V] in
/-- Full-edge odd-list transport at a defender node.  Any supplied odd list of
legal defender branches lifts to a parent response moment.  Completeness of the
list is not an assumption or a conclusion of this theorem. -/
theorem AffineResponseMoment.answer_odd_fan_zero
    {G : SimpleGraph V} {seat : Bool} {s : State V}
    {hseat : s.toMove = seat}
    {hasMove : ∃ m u, step G s m = some u}
    {hchildren : ∀ m u, step G s m = some u → OddWins G seat u}
    {I : Type*} (is : List I) (m : I → Move V) (t : I → State V)
    (hstep : ∀ i ∈ is, step G s (m i) = some (t i))
    (z : I → EdgeVector V)
    (hz : ∀ i (hi : i ∈ is),
      AffineResponseMoment G seat (hchildren (m i) (t i) (hstep i hi)) (z i))
    (hodd : is.length % 2 = 1)
    (hsum : (is.map fun i ↦ moveLiveStar s (m i) + z i).sum = 0) :
    AffineResponseMoment G seat
      (OddWins.answer s hseat hasMove hchildren) 0 := by
  let parent := OddWins.answer s hseat hasMove hchildren
  have hlift : ∀ w ∈ (is.map fun i ↦ moveLiveStar s (m i) + z i),
      AffineResponseMoment G seat parent w := by
    intro w hw
    simp only [List.mem_map] at hw
    obtain ⟨i, hi, rfl⟩ := hw
    exact AffineResponseMoment.answerChild
      (hseat := hseat) (hasMove := hasMove) (hchildren := hchildren)
      (hstep := hstep i hi) (hz i hi)
  have hoddMap : (is.map fun i ↦
      moveLiveStar s (m i) + z i).length % 2 = 1 := by
    simpa using hodd
  rw [← hsum]
  exact AffineResponseMoment.odd_list_sum _ hoddMap hlift

omit [Fintype V] [DecidableEq V] in
private theorem list_sum_map_add {I : Type*} (is : List I)
    (f g : I → EdgeVector V) :
    (is.map fun i ↦ f i + g i).sum =
      (is.map f).sum + (is.map g).sum := by
  induction is with
  | nil => simp
  | cons i rest ih =>
      simp only [List.map_cons, List.sum_cons]
      rw [ih]
      abel

omit [Fintype V] in
/-- Continuation-coset form of odd-list defender transport.  If the aggregate
base defect belongs to the sum of the selected child direction spaces, the
parent response affine space contains zero.  This theorem assumes the selected
list and its factor equation; it does not construct a complete fan. -/
theorem AffineResponseMoment.answer_factor_extension
    {G : SimpleGraph V} {seat : Bool} {s : State V}
    {hseat : s.toMove = seat}
    {hasMove : ∃ m u, step G s m = some u}
    {hchildren : ∀ m u, step G s m = some u → OddWins G seat u}
    {I : Type*} (is : List I) (m : I → Move V) (t : I → State V)
    (hstep : ∀ i ∈ is, step G s (m i) = some (t i))
    (a d : I → EdgeVector V)
    (ha : ∀ i (hi : i ∈ is),
      AffineResponseMoment G seat (hchildren (m i) (t i) (hstep i hi)) (a i))
    (hd : ∀ i (hi : i ∈ is),
      ResponseDirection G seat (hchildren (m i) (t i) (hstep i hi)) (d i))
    (hodd : is.length % 2 = 1)
    (hfactor : (is.map fun i ↦ moveLiveStar s (m i) + a i).sum =
      (is.map d).sum) :
    AffineResponseMoment G seat
      (OddWins.answer s hseat hasMove hchildren) 0 := by
  have had : ∀ i (hi : i ∈ is),
      AffineResponseMoment G seat
        (hchildren (m i) (t i) (hstep i hi)) (a i + d i) := by
    intro i hi
    exact (ha i hi).add_direction (hd i hi)
  have hdecomp :
      (is.map fun i ↦ moveLiveStar s (m i) + (a i + d i)).sum =
        (is.map fun i ↦ moveLiveStar s (m i) + a i).sum +
          (is.map d).sum := by
    simpa only [add_assoc] using list_sum_map_add is
      (fun i ↦ moveLiveStar s (m i) + a i) d
  have hzero :
      (is.map fun i ↦ moveLiveStar s (m i) + (a i + d i)).sum = 0 := by
    rw [hdecomp, hfactor]
    ext e
    exact CharTwo.add_self_eq_zero _
  exact AffineResponseMoment.answer_odd_fan_zero
    (hseat := hseat) (hasMove := hasMove) (hchildren := hchildren)
    is m t hstep (fun i ↦ a i + d i) had hodd hzero

/-- A proof-indexed ancestry path in one fixed odd strategy tree, carrying the
sum of universal live-star charges on its root-to-node prefix. -/
inductive StrategyPrefix (G : SimpleGraph V) (seat : Bool)
    {root : State V} (hroot : OddWins G seat root) :
    {s : State V} → OddWins G seat s → EdgeVector V → Prop
  | root : StrategyPrefix G seat hroot hroot 0
  | choose {s s' : State V} {hseat : s.toMove ≠ seat}
      {m : Move V} {hstep : step G s m = some s'}
      {hchild : OddWins G seat s'} {p : EdgeVector V}
      (parent : StrategyPrefix G seat hroot
        (OddWins.choose s hseat m s' hstep hchild) p) :
      StrategyPrefix G seat hroot hchild (p + moveLiveStar s m)
  | answer {s s' : State V} {hseat : s.toMove = seat}
      {hasMove : ∃ m u, step G s m = some u}
      {hchildren : ∀ m u, step G s m = some u → OddWins G seat u}
      {m : Move V} {hstep : step G s m = some s'} {p : EdgeVector V}
      (parent : StrategyPrefix G seat hroot
        (OddWins.answer s hseat hasMove hchildren) p) :
      StrategyPrefix G seat hroot (hchildren m s' hstep)
        (p + moveLiveStar s m)

omit [Fintype V] in
/-- A continuation representative at an ancestry node lifts to the root by
adding the prefix live-star moment. -/
theorem StrategyPrefix.lift
    {G : SimpleGraph V} {seat : Bool} {root s : State V}
    {hroot : OddWins G seat root} {h : OddWins G seat s}
    {p z : EdgeVector V} (hp : StrategyPrefix G seat hroot h p)
    (hz : AffineResponseMoment G seat h z) :
    AffineResponseMoment G seat hroot (p + z) := by
  induction hp generalizing z with
  | root => simpa using hz
  | @choose s s' hseat m hstep hchild p parent ih =>
      have hparent : AffineResponseMoment G seat
          (OddWins.choose s hseat m s' hstep hchild)
          (moveLiveStar s m + z) :=
        .choose (hseat := hseat) (hstep := hstep) hz
      simpa only [add_assoc] using ih hparent
  | @answer s s' hseat hasMove hchildren m hstep p parent ih =>
      have hparent : AffineResponseMoment G seat
          (OddWins.answer s hseat hasMove hchildren)
          (moveLiveStar s m + z) :=
        .answerChild (hseat := hseat) (hasMove := hasMove)
          (hchildren := hchildren) (hstep := hstep) hz
      simpa only [add_assoc] using ih hparent

/-- One proof-indexed ancestry hole, retaining the exact descendant strategy
proof and its prefix moment.  No antichain or closure condition is imposed. -/
structure StrategyHole (G : SimpleGraph V) (seat : Bool)
    {root : State V} (hroot : OddWins G seat root) where
  state : State V
  tree : OddWins G seat state
  moment : EdgeVector V
  ancestry : StrategyPrefix G seat hroot tree moment

omit [Fintype V] in
/-- Full-edge proof-indexed ancestry factor extension.  The selected holes may lie in
different defender siblings and at different FIFO-front levels.  If their
aggregate prefix-plus-base defect belongs to the sum of their continuation
direction spaces, the root response affine space contains zero. -/
theorem StrategyHole.factor_extension_zero
    {G : SimpleGraph V} {seat : Bool} {root : State V}
    {hroot : OddWins G seat root} {I : Type*}
    (is : List I) (hole : I → StrategyHole G seat hroot)
    (a d : I → EdgeVector V)
    (ha : ∀ i ∈ is, AffineResponseMoment G seat (hole i).tree (a i))
    (hd : ∀ i ∈ is, ResponseDirection G seat (hole i).tree (d i))
    (hodd : is.length % 2 = 1)
    (hfactor : (is.map fun i ↦ (hole i).moment + a i).sum =
      (is.map d).sum) :
    AffineResponseMoment G seat hroot 0 := by
  have had : ∀ i (hi : i ∈ is),
      AffineResponseMoment G seat (hole i).tree (a i + d i) := by
    intro i hi
    exact (ha i hi).add_direction (hd i hi)
  have hlift : ∀ i (hi : i ∈ is),
      AffineResponseMoment G seat hroot
        ((hole i).moment + (a i + d i)) := by
    intro i hi
    exact (hole i).ancestry.lift (had i hi)
  have hdecomp :
      (is.map fun i ↦ (hole i).moment + (a i + d i)).sum =
        (is.map fun i ↦ (hole i).moment + a i).sum +
          (is.map d).sum := by
    simpa only [add_assoc] using list_sum_map_add is
      (fun i ↦ (hole i).moment + a i) d
  have hzero :
      (is.map fun i ↦ (hole i).moment + (a i + d i)).sum = 0 := by
    rw [hdecomp, hfactor]
    ext e
    exact CharTwo.add_self_eq_zero _
  have hmem : ∀ w ∈
      (is.map fun i ↦ (hole i).moment + (a i + d i)),
      AffineResponseMoment G seat hroot w := by
    intro w hw
    simp only [List.mem_map] at hw
    obtain ⟨i, hi, rfl⟩ := hw
    exact hlift i hi
  have hoddMap :
      (is.map fun i ↦ (hole i).moment + (a i + d i)).length % 2 = 1 := by
    simpa using hodd
  rw [← hzero]
  exact AffineResponseMoment.odd_list_sum _ hoddMap hmem

/-- A finite ancestry factor term: one proof-indexed hole, one continuation
base representative, and one available direction in that continuation. -/
structure StrategyFactorTerm (G : SimpleGraph V) (seat : Bool)
    {root : State V} (hroot : OddWins G seat root) where
  hole : StrategyHole G seat hroot
  base : EdgeVector V
  correction : EdgeVector V
  base_mem : AffineResponseMoment G seat hole.tree base
  correction_mem : ResponseDirection G seat hole.tree correction

/-- A strong full-edge factor certificate.  Because `EdgeVector V` retains
dummy-incident and diagonal coordinates, this is stronger than the exact real-edge
certificate below. -/
structure StrategyFactorCertificate (G : SimpleGraph V) (seat : Bool)
    {root : State V} (hroot : OddWins G seat root) where
  terms : List (StrategyFactorTerm G seat hroot)
  odd : terms.length % 2 = 1
  factor : (terms.map fun t ↦ t.hole.moment + t.base).sum =
    (terms.map fun t ↦ t.correction).sum

omit [Fintype V] in
/-- Any factor certificate contracts the corresponding odd strategy's root
response affine space to zero. -/
theorem StrategyFactorCertificate.zero
    {G : SimpleGraph V} {seat : Bool} {root : State V}
    {hroot : OddWins G seat root}
    (h : StrategyFactorCertificate G seat hroot) :
    AffineResponseMoment G seat hroot 0 := by
  exact StrategyHole.factor_extension_zero h.terms
    (fun t ↦ t.hole) (fun t ↦ t.base) (fun t ↦ t.correction)
    (fun t _ ↦ t.base_mem) (fun t _ ↦ t.correction_mem) h.odd h.factor

/-- The exact real-edge factor certificate.  Its balance equation is imposed
only after quotienting by non-real coordinates; all proof-indexed
continuation membership data remain in the universal edge space. -/
structure ProjectedStrategyFactorCertificate (G : SimpleGraph V) (d : V)
    (seat : Bool) {root : State V} (hroot : OddWins G seat root) where
  terms : List (StrategyFactorTerm G seat hroot)
  odd : terms.length % 2 = 1
  factor :
    realEdgeProjection d
        ((terms.map fun t ↦ t.hole.moment + t.base).sum) =
      realEdgeProjection d ((terms.map fun t ↦ t.correction).sum)

/-- Every strong full-edge certificate descends to an exact real-edge
certificate.  The converse is not assumed: the quotient intentionally forgets
non-real coordinates. -/
def StrategyFactorCertificate.toProjected
    {G : SimpleGraph V} {seat : Bool} {root : State V}
    {hroot : OddWins G seat root}
    (h : StrategyFactorCertificate G seat hroot) (d : V) :
    ProjectedStrategyFactorCertificate G d seat hroot where
  terms := h.terms
  odd := h.odd
  factor := congrArg (realEdgeProjection d) h.factor

omit [Fintype V] in
/-- A projected factor certificate contracts the root response affine space
to zero in the real-edge quotient. -/
theorem ProjectedStrategyFactorCertificate.zero
    {G : SimpleGraph V} {d : V} {seat : Bool} {root : State V}
    {hroot : OddWins G seat root}
    (h : ProjectedStrategyFactorCertificate G d seat hroot) :
    ProjectedAffineResponseMoment d G seat hroot 0 := by
  have had : ∀ t ∈ h.terms,
      AffineResponseMoment G seat t.hole.tree
        (t.base + t.correction) := by
    intro t _
    exact t.base_mem.add_direction t.correction_mem
  have hlift : ∀ t ∈ h.terms,
      AffineResponseMoment G seat hroot
        (t.hole.moment + (t.base + t.correction)) := by
    intro t ht
    exact t.hole.ancestry.lift (had t ht)
  let z :=
    (h.terms.map fun t ↦
      t.hole.moment + (t.base + t.correction)).sum
  have hmem : ∀ w ∈
      (h.terms.map fun t ↦
        t.hole.moment + (t.base + t.correction)),
      AffineResponseMoment G seat hroot w := by
    intro w hw
    simp only [List.mem_map] at hw
    obtain ⟨t, ht, rfl⟩ := hw
    exact hlift t ht
  have hresponse : AffineResponseMoment G seat hroot z := by
    apply AffineResponseMoment.odd_list_sum
    · simpa [z] using h.odd
    · simpa [z] using hmem
  have hdecomp :
      z =
        (h.terms.map fun t ↦ t.hole.moment + t.base).sum +
          (h.terms.map fun t ↦ t.correction).sum := by
    simpa only [z, add_assoc] using list_sum_map_add h.terms
      (fun t ↦ t.hole.moment + t.base) (fun t ↦ t.correction)
  refine ⟨z, hresponse, ?_⟩
  rw [hdecomp, map_add, h.factor]
  rw [← map_add]
  have hself :
      (h.terms.map fun t ↦ t.correction).sum +
          (h.terms.map fun t ↦ t.correction).sum = 0 := by
    ext e
    exact CharTwo.add_self_eq_zero _
  rw [hself, map_zero]

omit [Fintype V] in
/-- A projected root response moment gives a one-term projected certificate.
This deliberately exposes the proof boundary: without a restriction on which
ancestry holes may be used, certificate existence is an exact repackaging of
the projected affine target rather than a smaller construction theorem. -/
theorem ProjectedAffineResponseMoment.nonempty_strategyFactorCertificate
    {G : SimpleGraph V} {d : V} {seat : Bool} {root : State V}
    {hroot : OddWins G seat root}
    (h : ProjectedAffineResponseMoment d G seat hroot 0) :
    Nonempty (ProjectedStrategyFactorCertificate G d seat hroot) := by
  obtain ⟨z, hz, hprojection⟩ := h
  let hole : StrategyHole G seat hroot := {
    state := root
    tree := hroot
    moment := 0
    ancestry := StrategyPrefix.root }
  let term : StrategyFactorTerm G seat hroot := {
    hole := hole
    base := z
    correction := 0
    base_mem := hz
    correction_mem := ResponseDirection.zero hroot }
  refine ⟨{
    terms := [term]
    odd := by simp
    factor := ?_ }⟩
  simp [term, hole, hprojection]

omit [Fintype V] in
/-- Unrestricted projected ancestry certificates are equivalent to the root
projected affine target.  Their value is compositional: future work must
construct one from a genuinely restricted causal frontier for this language
to reduce the open theorem. -/
theorem nonempty_projectedStrategyFactorCertificate_iff
    {G : SimpleGraph V} {d : V} {seat : Bool} {root : State V}
    {hroot : OddWins G seat root} :
    Nonempty (ProjectedStrategyFactorCertificate G d seat hroot) ↔
      ProjectedAffineResponseMoment d G seat hroot 0 := by
  constructor
  · rintro ⟨h⟩
    exact h.zero
  · intro h
    exact h.nonempty_strategyFactorCertificate

/-- Strong full-edge form of the still-open construction. -/
def InitialAncestryFactorExtensionAt
    (G : SimpleGraph V) (d : V) (seat : Bool) : Prop :=
  IsDummy G d → ∀ h : OddWins G seat (initial (V := V)),
    Nonempty (StrategyFactorCertificate G seat h)

/-- The strong full-edge ancestry factor-extension statement is sufficient
for the pointwise FIFO linking theorem.  This theorem proves only the
implication; it does not construct the hypothesis. -/
theorem initialAncestryFactorExtensionAt_implies_linking
    {G : SimpleGraph V} {d : V} {seat : Bool}
    (hfactor : InitialAncestryFactorExtensionAt G d seat)
    (hd : IsDummy G d) : EvenWins G seat (initial (V := V)) := by
  rw [linking_at_iff_noOddCounterstrategy hd]
  intro hodd
  obtain ⟨hcertificate⟩ := hfactor hd hodd
  exact no_zero_affineResponseMoment_initial hcertificate.zero

/-- Exact real-edge form of the still-open construction: every explicit odd
strategy at an isolated-dummy root admits a projected ancestry factor
certificate. -/
def InitialProjectedAncestryFactorExtensionAt
    (G : SimpleGraph V) (d : V) (seat : Bool) : Prop :=
  IsDummy G d → ∀ h : OddWins G seat (initial (V := V)),
    Nonempty (ProjectedStrategyFactorCertificate G d seat h)

/-- The projected ancestry factor-extension statement is sufficient for the
pointwise FIFO linking theorem. -/
theorem initialProjectedAncestryFactorExtensionAt_implies_linking
    {G : SimpleGraph V} {d : V} {seat : Bool}
    (hfactor : InitialProjectedAncestryFactorExtensionAt G d seat)
    (hd : IsDummy G d) : EvenWins G seat (initial (V := V)) := by
  rw [linking_at_iff_noOddCounterstrategy hd]
  intro hodd
  obtain ⟨hcertificate⟩ := hfactor hd hodd
  exact no_zero_projectedAffineResponseMoment_initial hd hcertificate.zero

/-- At a fixed isolated-dummy board, the unrestricted projected certificate
statement is equivalent to pointwise FIFO linking.  This prevents the
certificate language itself from being mistaken for a proof reduction. -/
theorem initialProjectedAncestryFactorExtensionAt_iff_linking
    {G : SimpleGraph V} {d : V} {seat : Bool} (hd : IsDummy G d) :
    InitialProjectedAncestryFactorExtensionAt G d seat ↔
      EvenWins G seat (initial (V := V)) := by
  constructor
  · intro hfactor
    exact initialProjectedAncestryFactorExtensionAt_implies_linking hfactor hd
  · intro heven _ hodd
    have hno : ¬OddWins G seat (initial (V := V)) :=
      (linking_at_iff_noOddCounterstrategy hd seat).mp heven
    exact False.elim (hno hodd)

end

end Ogdoad.Fifo
