//! Integer row-lattice reduction used by quotient constructions.

fn leading(row: &[i128]) -> Option<usize> {
    row.iter().position(|&x| x != 0)
}

fn row_is_zero(row: &[i128]) -> bool {
    row.iter().all(|&x| x == 0)
}

fn checked_abs(x: i128) -> i128 {
    x.checked_abs()
        .expect("integer relation coefficient magnitude exceeds i128")
}

fn negate_row(row: &mut [i128]) {
    for x in row {
        *x = x
            .checked_neg()
            .expect("integer relation coefficient magnitude exceeds i128");
    }
}

fn sub_row_multiple(target: &mut [i128], source: &[i128], q: i128) {
    for (t, &s) in target.iter_mut().zip(source) {
        let delta = q
            .checked_mul(s)
            .expect("integer relation row operation exceeds i128");
        *t = t
            .checked_sub(delta)
            .expect("integer relation row operation exceeds i128");
    }
}

/// Row Hermite-style normal form for an integer row lattice.
///
/// The returned rows generate exactly the same submodule as the input rows, have
/// increasing leading columns, positive pivots, zeros below each pivot, and
/// residues above pivots reduced modulo the pivot.
pub(crate) fn normalize_relation_rows(mut rows: Vec<Vec<i128>>) -> Vec<Vec<i128>> {
    let width = rows.first().map_or(0, Vec::len);
    assert!(
        rows.iter().all(|r| r.len() == width),
        "integer relation rows must have equal width"
    );
    rows.retain(|r| !row_is_zero(r));
    let mut rank = 0usize;
    for col in 0..width {
        let Some(pivot) = (rank..rows.len()).find(|&r| rows[r][col] != 0) else {
            continue;
        };
        rows.swap(rank, pivot);
        if rows[rank][col] < 0 {
            negate_row(&mut rows[rank]);
        }

        while let Some(r) = ((rank + 1)..rows.len()).find(|&r| rows[r][col] != 0) {
            let pivot_val = rows[rank][col];
            let q = rows[r][col].div_euclid(pivot_val);
            let source = rows[rank].clone();
            sub_row_multiple(&mut rows[r], &source, q);
            if rows[r][col] != 0 && checked_abs(rows[r][col]) < checked_abs(rows[rank][col]) {
                rows.swap(rank, r);
                if rows[rank][col] < 0 {
                    negate_row(&mut rows[rank]);
                }
            }
        }

        if rows[rank][col] < 0 {
            negate_row(&mut rows[rank]);
        }
        let pivot_val = rows[rank][col];
        let source = rows[rank].clone();
        for r in 0..rows.len() {
            if r == rank || rows[r][col] == 0 {
                continue;
            }
            let q = rows[r][col].div_euclid(pivot_val);
            sub_row_multiple(&mut rows[r], &source, q);
        }
        rank += 1;
    }
    rows.retain(|r| !row_is_zero(r));
    rows.sort_by_key(|r| leading(r).unwrap_or(usize::MAX));
    rows
}

/// Reduce `v` to a canonical representative modulo the row lattice generated by
/// `rows`.
pub(crate) fn reduce_integer_vector(v: &mut [i128], rows: Vec<Vec<i128>>) {
    for row in normalize_relation_rows(rows) {
        let Some(lead) = leading(&row) else {
            continue;
        };
        let pivot = row[lead];
        debug_assert!(pivot > 0);
        let q = v[lead].div_euclid(pivot);
        if q != 0 {
            for i in 0..v.len() {
                v[i] -= q * row[i];
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalizes_shared_divisor_rows() {
        let rows = vec![vec![2, 0], vec![3, 0]];
        assert_eq!(normalize_relation_rows(rows), vec![vec![1, 0]]);
    }

    #[test]
    fn reduction_handles_coupled_relations() {
        let rows = vec![vec![2, 4], vec![6, 10]];
        let mut v = vec![8, 14];
        reduce_integer_vector(&mut v, rows.clone());
        assert_eq!(v, vec![0, 0]);

        let mut shifted = vec![9, 14];
        reduce_integer_vector(&mut shifted, rows);
        assert_ne!(shifted, vec![0, 0]);
    }
}
